from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
# from.views import errorpage

urlpatterns =[
    path('',views.index,name=''),
    path('index',views.index,name='index'),
    path('userlogin',views.userlogin,name='userlogin'),
    path('shop',views.shop,name='shop'),
    path('about',views.about,name='about'),
    path('blog',views.blog,name='blog'),
    path('contact',views.contact,name='contact'),
    path('cart',views.cart,name='cart'),
    path('checkout',views.checkout,name='checkout'),
    path('thankyou',views.thankyou,name='thankyou'),
    path('usersignup',views.usersignup,name='usersignup'),
    path('signup',views.signup,name='signup'),
    path('logi',views.logi,name='logi'),
    path('userhome',views.userhome,name='userhome'),
    path('logout',views.logout,name='logout'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('userlist',views.userlist,name='userlist'),
    path('categorylist',views.categorylist,name='categorylist'),
    path('orderlist',views.orderlist,name='orderlist'),
    path('productlist',views.productlist,name='productlist'),
    path('product',views.product,name='product'),
    path('category',views.category,name='category'),
    path('orderhistory',views.orderhistory,name='orderhistory'),
    path('privacy',views.privacy,name='privacy'),
    path('profile',views.profile,name='profile'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('blockusr',views.blockusr,name='blockusr'),
    path('unblockusr',views.unblockusr,name='unblockusr'),
    path('caty',views.caty,name='caty'),
    path('delcat',views.delcat,name='delcat'),
    path('editcat',views.editcat,name='editcat'),
    path('adpro',views.adpro,name='adpro'),
    path('delpro',views.delpro,name='delpro'),
    path('editpro',views.editpro,name='editpro'),
    path('addtocart',views.addtocart,name='addtocart'),
    path('delcartitem',views.delcartitem,name='delcartitem'),
    path('otpverification/<int:userid>/<str:secret>',views.otpverification,name='otpverification'),
    path('verification/<int:userid>/<str:secret>',views.verification,name='verification'),
    path('productdetail',views.productdetail,name='productdetail'),
    path('inccartitem',views.inccartitem,name='inccartitem'),
    path('deccartitem',views.deccartitem,name='deccartitem'),
    path('adprivacy',views.adprivacy,name='adprivacy'),
    path('forgot',views.forgot,name='forgot'),
    path('newpwd',views.newpwd,name='newpwd'),
    path('forg',views.forg,name='forg'),
    path('aprivacy',views.aprivacy,name='aprivacy'),
    path('uprivacy',views.uprivacy,name='uprivacy'),
    path('categorywise',views.categorywise,name='categorywise'),
    path('address',views.address,name='address'),
    path('shipped',views.shipped,name='shipped'),
    path('cancel',views.cancel,name='cancel'),
    path('paypal',views.paypal,name='paypal'),
    path('updateprofile',views.updateprofile,name='updateprofile'),
    path('usorcan',views.usorcan,name='usorcan'),
    path('completed',views.completed,name='completed'),
    path('offer',views.offer,name='offer'),
    path('offerlist',views.offerlist,name='offerlist'),
    path('addoffer',views.addoffer,name='addoffer'),
    path('deloffer',views.deloffer,name='deloffer'),
    path('updateoffer',views.updateoffer,name='updateoffer'),
    path('catoffer',views.catoffer,name='catoffer'),
    path('delcatoffer',views.delcatoffer,name='delcatoffer'),
    path('proffer',views.proffer,name='proffer'),
    path('reproffer',views.reproffer,name='reproffer'),
    path('productdet',views.productdet,name='productdet'),
    path('ordreturn',views.ordreturn,name='ordreturn'),
    path('refund',views.refund,name='refund'),
    path('reportpdf',views.reportpdf,name='reportpdf'),
    path('banner',views.banner,name='banner'),
    path('bannerlist',views.bannerlist,name='bannerlist'),
    path('delbanner',views.delbanner,name='delbanner'),
    path('deladdress',views.deladdress,name='deladdress'),
    path('editaddress',views.editaddress,name='editaddress'),
    path('newaddress',views.newaddress,name='newaddress'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)