# Generated by Django 3.2.16 on 2023-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='couponapplied',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordernotes',
            field=models.CharField(max_length=255, null=True, verbose_name='ordernotes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='waiting', max_length=20, verbose_name='status'),
        ),
    ]
