# Generated by Django 3.2.16 on 2023-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20230207_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('bannerid', models.AutoField(primary_key=True, serialize=False)),
                ('banner', models.FileField(upload_to='banners/', verbose_name='banner')),
            ],
        ),
    ]
